server:
  port: 8771


#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: product-service

    #zipkin服务所在地址
  zipkin:
    base-url: http://47.113.106.197:9411